### ISSUE TITLE
Transferprocess Complete returns 404 

### ISSUE THREAD

**Issue by hamidonos** [eclipse-edc/Samples#126]
# Bug Report

Consumer returns 404 when provider calls http://localhost:9191/api/v1/control/transferprocess/7ed1f3d1-f0c0-42a8-971d-8616b4225637/complete after file transfer has been completed successfully

Provider logs:
```
...
DEBUG 2023-09-27T15:40:44.657925 TransferProcess 7ed1f3d1-f0c0-42a8-971d-8616b4225637 is now in state COMPLETED
SEVERE 2023-09-27T15:41:00.758912 Failed to send callback request
org.eclipse.edc.spi.http.EdcHttpClientException: Server response to Request{method=POST, url=http://localhost:9191/api/v1/control/transferprocess/7ed1f3d1-f0c0-42a8-971d-8616b4225637/complete} was not 200 but was 404: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
...
```

Consumer logs:

```
...
DEBUG 2023-09-27T15:40:44.65884 TransferProcess 3f501c02-3b12-40fe-81c9-6b00a7478c85 is now in state COMPLETED
SEVERE 2023-09-27T15:40:45.167901 JerseyExtension: Unexpected exception caught
jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:258)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
...
```

### Expected Behavior

Call should return 200 and throw no exception

## Steps to Reproduce

Setup a transfer sample 01 and perform a data transfer

**Comment by hamidonos** [comment]
For some reason it returns 405 with Sample 02

DEBUG 2023-09-28T09:43:56.188051 TransferProcess 4d07f71d-df6d-43ca-9e22-9dc2691aba9f is now in state COMPLETED
SEVERE 2023-09-28T09:44:12.696857 Failed to send callback request
org.eclipse.edc.spi.http.EdcHttpClientException: Server response to Request{method=POST, url=http://localhost:9191/api/v1/control/transferprocess/4d07f71d-df6d-43ca-9e22-9dc2691aba9f/complete} was not 200 but was 405: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 405 HTTP method POST is not supported by this URL</title>
</head>
<body><h2>HTTP ERROR 405 HTTP method POST is not supported by this URL</h2>
<table>
<tr><th>URI:</th><td>/api/v1/control/transferprocess/4d07f71d-df6d-43ca-9e22-9dc2691aba9f/complete</td></tr>
<tr><th>STATUS:</th><td>405</td></tr>
<tr><th>MESSAGE:</th><td>HTTP method POST is not supported by this URL</td></tr>
<tr><th>SERVLET:</th><td>org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-6cea706c</td></tr>
</table>

**Comment by ndr-brt** [comment]
Looks like the `edc.control.endpoint` has not been configured, from version 0.3.0 the data plane needs to communicate with the control-plane, by [default that endpoint falls back to the hostname configuration](https://github.com/eclipse-edc/Connector/blob/bbfcbabd564cc4b4bc1d76a7691318203670a80f/extensions/common/api/control-api-configuration/src/main/java/org/eclipse/edc/connector/api/control/configuration/ControlApiConfigurationExtension.java#L45-L46).

I don't know on which sample you encountered the error, but configuring that endpoint correctly will fix the issue.

**Comment by jerzy-wachowiak** [comment]
EDC0.5.1 The same issue on CX INT...

**Comment by ndr-brt** [comment]
> EDC0.5.1 The same issue on CX INT...

I think you are referring to a different project, this is the Samples repositories, not meant to be used in production

**Comment by jerzy-wachowiak** [comment]
Yes, your are right but it is probably the same problem...

**Comment by ndr-brt** [comment]
the sample is a customization of the data plane and it has issues because it has not been maintained properly, on CX the extensions are well maintained so I don't think it could be the same issue, but, I would be happy to be denied.
In every case, as I already said in a past comment, we'd need to move this sample and likely to update it properly
