### ISSUE TITLE
Sample 04 (OpenTelementry) docker container fails

### ISSUE THREAD

**Issue by hamidonos** [eclipse-edc/Samples#127]
# Bug Report

## Describe the Bug

transfer-04-open-telemetry-provider-1  | 2023-09-28 08:22:59 WARNING : Configuration file does not exist: dataspaceconnector-configuration.properties. Ignoring. 
transfer-04-open-telemetry-consumer-1  | 2023-09-28 08:22:59 WARNING : Configuration file does not exist: dataspaceconnector-configuration.properties. Ignoring. 
transfer-04-open-telemetry-consumer-1  | 2023-09-28 08:22:59 INFO : Initialized FS Configuration 
transfer-04-open-telemetry-provider-1  | 2023-09-28 08:22:59 INFO : Initialized FS Configuration 
transfer-04-open-telemetry-provider-1  | 2023-09-28 08:22:59 WARNING : The runtime is configured as an anonymous participant. DO NOT DO THIS IN PRODUCTION. 
transfer-04-open-telemetry-consumer-1  | 2023-09-28 08:22:59 WARNING : The runtime is configured as an anonymous participant. DO NOT DO THIS IN PRODUCTION. 
transfer-04-open-telemetry-provider-1  | 2023-09-28 08:22:59 SEVERE : Error booting runtime: The following injected fields were not provided: Field "transferProcessApiClient" of type [interface org.eclipse.edc.connector.api.client.spi.transferprocess.TransferProcessApiClient] required by org.eclipse.edc.connector.dataplane.framework.DataPlaneFrameworkExtension 
transfer-04-open-telemetry-consumer-1  | 2023-09-28 08:22:59 SEVERE : Error booting runtime: The following injected fields were not provided: Field "dataPlaneInstanceStore" of type [interface org.eclipse.edc.connector.dataplane.selector.spi.store.DataPlaneInstanceStore] required by org.eclipse.edc.connector.catalog.CatalogDefaultServicesExtension 
transfer-04-open-telemetry-provider-1 exited with code 255
Aborting on container exit...

### Expected Behavior

Container starts

## Steps to Reproduce

Run the sample: 
1. ./gradlew transfer:transfer-04-open-telemetry:open-telemetry-consumer:build transfer:transfer-04-open-telemetry:open-telemetry-provider:build
2. docker-compose -f transfer/transfer-04-open-telemetry/docker-compose.yaml up --abort-on-container-exit

## Possible Implementation

Provide configuration for: 

- transferProcessApiClient
- dataPlaneInstanceStore

**Comment by ndr-brt** [comment]
someone already tried but never brought the PR to a read-to-be-merged state: https://github.com/eclipse-edc/Samples/pull/92, it could be a good starting point
