### ISSUE TITLE
Sample transfer-06-consumer-pull-http error running the connectors

### ISSUE THREAD

**Issue by ivantrojnar** [eclipse-edc/Samples#133]
Following the sample transfer 06, after building the connector I try to run the commands to start the connectors. After running the commands which I got from the README.md file: 
INFO 2023-10-10T07:58:50.1484593 Initialized FS Configuration
SEVERE 2023-10-10T07:58:51.9009282 Error booting runtime: The following injected fields were not provided: Field "transferProcessApiClient" of type [interface org.eclipse.edc.connector.api.client.spi.transferprocess.TransferProcessApiClient] required by org.eclipse.edc.connector.dataplane.framework.DataPlaneFrameworkExtension
org.eclipse.edc.spi.system.injection.EdcInjectionException: The following injected fields were not provided:
Field "transferProcessApiClient" of type [interface org.eclipse.edc.connector.api.client.spi.transferprocess.TransferProcessApiClient] required by org.eclipse.edc.connector.dataplane.framework.DataPlaneFrameworkExtension
        at org.eclipse.edc.boot.system.DependencyGraph.of(DependencyGraph.java:102)
        at org.eclipse.edc.boot.system.ExtensionLoader.loadServiceExtensions(ExtensionLoader.java:119)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.createExtensions(BaseRuntime.java:151)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:201)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:84)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:72)

This is the command I used to run the provider connector: java -Dedc.keystore=transfer/transfer-06-consumer-pull-http/certs/cert.pfx -Dedc.keystore.password=123456 -Dedc.vault=transfer/transfer-06-consumer-pull-http/http-pull-provider/provider-vault.properties -Dedc.fs.config=transfer/transfer-06-consumer-pull-http/http-pull-provider/provider-configuration.properties -jar transfer/transfer-06-consumer-pull-http/http-pull-connector/build/libs/pull-connector.jar 

This is the command I used to run the consumer connector:  java -Dedc.keystore=transfer/transfer-06-consumer-pull-http/certs/cert.pfx -Dedc.keystore.password=123456 -Dedc.vault=transfer/transfer-06-consumer-pull-http/http-pull-consumer/consumer-vault.properties -Dedc.fs.config=transfer/transfer-06-consumer-pull-http/http-pull-consumer/consumer-configuration.properties -jar transfer/transfer-06-consumer-pull-http/http-pull-connector/build/libs/pull-connector.jar

Both commands give the same error

**Comment by MichaelSteinert** [comment]
You can add the following implementation to `build.gradle.kts` in sample 6 to run the Connector.

`
dependencies {
    implementation("org.eclipse.edc:control-plane-api-client:0.3.1")
}
`

This is the implementation that is called by the interface that is loaded by Java SPI through the Connector.

**Comment by ndr-brt** [comment]
just for the record, the solution was applied in https://github.com/eclipse-edc/Samples/pull/129
