### ISSUE TITLE
Whether data from a database can be published as a data asset (e.g. postgresql)

### ISSUE THREAD

**Issue by fcm2000105** [eclipse-edc/Samples#169]
If I want to publish the data resources of the postgres database, how should I modify the file create-asset.json, and do I need to modify anything else?

{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "assetId",
  "properties": {
    "name": "product description",
    "contenttype": "application/json"
  },
  "dataAddress": {
    "type": "HttpData",
    "name": "Test asset",
    "baseUrl": "https://jsonplaceholder.typicode.com/users",
    "proxyPath": "true"
  }
}

**Comment by ndr-brt** [comment]
You'd need to develop a extension for letting the data-plane interact with the postgresql database.
Please take a look at the [`data-plane-http` extension](https://github.com/eclipse-edc/Connector/tree/main/extensions/data-plane/data-plane-http) to see what it needs to be done

**Comment by fcm2000105** [comment]
Thank you very much! I will give it a try.
