### ISSUE TITLE
Management API version changed 

### ISSUE THREAD

**Issue by skante93** [eclipse-edc/Samples#172]
# Bug Report

When I was trying out the transfer samples for myself, in the [Transfer negociation step](../blob/main/transfer/transfer-01-negotiation/README.md#1-create-an-asset-on-the-provider-side), I found that the Management API version for assets should be "v3" not "v2", i.e the request should be:

```bash
curl -d @transfer/transfer-01-negotiation/resources/create-asset.json \
  -H 'content-type: application/json' http://localhost:19193/management/v3/assets \
  -s | jq
```

At least that is what worked for me not the v2.

**Comment by ndr-brt** [comment]
thanks for reporting, would you like to provide a PR to fix this?

**Comment by MichaelSteinert** [comment]
I have already made the changes in PR #165

**Comment by MichaelSteinert** [comment]
Done.
