### ISSUE TITLE
Issue fetching Retrieve provider Contract Offers

### ISSUE THREAD

**Issue by idrissyou** [eclipse-edc/Samples#236]
Hi, 
I'm exploring the Samples repository 
I have faced some challenges trying Samples/transfer/transfer-05-file-transfer-cloud
the example is trying to make a data exchange between 2 connector and  using blob storage and s3 bucket:

https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-05-file-transfer-cloud

- I was able to create the resources using the terraform script provided. 
- I adapted the the config.properties as asked in the doc. 
- I updated the seeder
- rebuild and run again. 
- the 2 connectors are up and running. 

I tried  request data offers from the provider, by running:

curl -X POST "http://localhost:9192/management/catalog/request" \
--header 'X-Api-Key: password' \
--header 'Content-Type: application/json' \
--data-raw '{
  "counterPartyAddress": "http://localhost:8282/protocol"
}'

I got the following response: 
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/management/catalog/request</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>EDC-management</td></tr>
</table>

</body>
</html>

```
I can see an error message on the provider as well 

```
Unexpected exception caught
jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:258)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)...
```
Is there anything that I'm missing? 

Thank you in advance 

![conf](https://github.com/eclipse-edc/Samples/assets/47866414/b014c19d-28be-4d76-be30-98a27af9f71f)
![code](https://github.com/eclipse-edc/Samples/assets/47866414/58b4e422-80c3-440d-85d5-da086d7b3908)
![Screenshot 2024-04-10 152821](https://github.com/eclipse-edc/Samples/assets/47866414/8f888198-9530-4ad1-8d75-e0d9430082a2)

**Comment by bpetrovbg** [comment]
same issue here... :)

**Comment by bpetrovbg** [comment]
@idrissyou @wissembhl 
so, after some experimenting, it seems that this Sample has not been updated for a while...

Can you please try again with:

http://localhost:9192/management/v2/catalog/request

please, notice that this time we have "v2" in the endpoint
