### ISSUE TITLE
`transfer-01-negotiation` fails to create a policy

### ISSUE THREAD

**Issue by FlorianK13** [eclipse-edc/Samples#237]
# Bug Report

## Describe the Bug

Creating a policy as described in `transfer-01-negotiation`: [create a policy on the provider](https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-01-negotiation#2-create-a-policy-on-the-provider) fails. It does not register a policy called aPolicy.

Other requests, like registering assets or creating a contract, are working fine.

### Expected Behavior

Successfully set up a policy called aPolicy

### Observed Behavior

Instead when I run `curl -d @transfer/transfer-01-negotiation/resources/create-policy.json   -H 'content-type: application/json' http://localhost:19193/management/v2/policydefinitions   -s` I get an HTTP 400 Error.

## Steps to Reproduce

1.  follow the steps from `transfer-00-prerequisites` 
2. create an asset, as described in [1-create-an-asset-on-the-provider-side](https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-01-negotiation#1-create-an-asset-on-the-provider-side)
3. run `curl -d @transfer/transfer-01-negotiation/resources/create-policy.json   -H 'content-type: application/json' http://localhost:19193/management/v2/policydefinitions   -s`
4. get this HTTP Error 400 page:

    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
    <title>Error 400 Bad Request</title>
    </head>
    <body><h2>HTTP ERROR 400 Bad Request</h2>
    <table>
    <tr><th>URI:</th><td>/management/v2/policydefinitions</td></tr>
    <tr><th>STATUS:</th><td>400</td></tr>
    <tr><th>MESSAGE:</th><td>Bad Request</td></tr>
    <tr><th>SERVLET:</th><td>EDC-management</td></tr>
    </table>
    
    </body>
    </html>
5. Meanwhile, the provider connector logs this error:
- jakarta.ws.rs.BadRequestException: Failed to expand JsonObject: There wa a problem encountered loading a remote context [http://www.w3.org/ns/odrl.jsonld]

## Context Information

- OS: Windows
- openjdk 17 2021-09-14

## Possible Implementation

As the `create-policy.json` file was recently changed (see [here](https://github.com/eclipse-edc/Samples/commits/main/transfer/transfer-01-negotiation/resources/create-policy.json)), maybe the error lies here?

**Comment by ndr-brt** [comment]
hey, EDC is not officially supporting Windows OS, please run the sample in a posix machine.

specifically, there was an issue related to this problem: https://github.com/eclipse-edc/Connector/issues/3687

**Comment by FlorianK13** [comment]
Yes, sorry didn't see that - now it works.
