### ISSUE TITLE
400 Bad request while trying transfer-01-negotiation sample

### ISSUE THREAD

**Issue by subhi-huawei** [eclipse-edc/Samples#241]
# Bug Report

## Describe the Bug

400 Bad request while trying transfer-01-negotiation sample

### Expected Behavior

Response should be 200

### Observed Behavior

Response is 400

## Steps to Reproduce

1. Run the provider:

```bash
java -Dedc.keystore=transfer/transfer-00-prerequisites/resources/certs/cert.pfx -Dedc.keystore.password=123456 -Dedc.vault=transfer/transfer-00-prerequisites/resources/configuration/provider-vault.properties -Dedc.fs.config=transfer/transfer-00-prerequisites/resources/configuration/provider-configuration.properties -jar transfer/transfer-00-prerequisites/connector/build/libs/connector.jar
```

2. Run the consumer:

```bash
java -Dedc.keystore=transfer/transfer-00-prerequisites/resources/certs/cert.pfx -Dedc.keystore.password=123456 -Dedc.vault=transfer/transfer-00-prerequisites/resources/configuration/consumer-vault.properties -Dedc.fs.config=transfer/transfer-00-prerequisites/resources/configuration/consumer-configuration.properties -jar transfer/transfer-00-prerequisites/connector/build/libs/connector.jar
```
3.  Run this with Postman:
```
curl --location 'http://localhost:19193/management/v2/policydefinitions' \
--header 'content-type: application/json' \
--data-raw '{
    "@context": {
        "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
        "odrl": "https://www.w3.org/ns/odrl/2/"
    },
    "@id": "aPolicy",
    "policy": {
        "@context": "https://www.w3.org/ns/odrl.jsonld",
        "@type": "Set",
        "permission": [],
        "prohibition": [],
        "obligation": []
    }
}'
```

## Detailed Description
![image](https://github.com/eclipse-edc/Samples/assets/167179433/81fa84a4-448c-4656-8fb4-92b63c72e2b5)

## Possible Implementation

Take the @context from [the URL](https://www.w3.org/ns/odrl.jsonld) and paste it in the request body will solve the problem

**Comment by ndr-brt** [comment]
I guess you are on a Windows machine right? In that case switching to WSL should solve your issue because the window command line is not 100% supported.

**Comment by subhi-huawei** [comment]
I am facing the error when I call the service from postman, not while executing a command line

**Comment by ndr-brt** [comment]
it's a server issue, not a client one, my question was about from where you are running the connector, not the client :)

**Comment by subhi-huawei** [comment]
I run using the following command 
`java -Dedc.keystore=transfer/transfer-00-prerequisites/resources/certs/cert.pfx -Dedc.keystore.password=123456 -Dedc.vault=transfer/transfer-00-prerequisites/resources/configuration/provider-vault.properties -Dedc.fs.config=transfer/transfer-00-prerequisites/resources/configuration/provider-configuration.properties -jar transfer/transfer-00-prerequisites/connector/build/libs/connector.jar`

from terminal inside IntelliJ

**Comment by ndr-brt** [comment]
which os?

**Comment by subhi-huawei** [comment]
Windows 10

**Comment by ndr-brt** [comment]
> I guess you are on a Windows machine right? In that case switching to WSL should solve your issue because the window command line is not 100% supported.

so I already wrote the solution some comments ago ;)

**Comment by subhi-huawei** [comment]
I tried with WSL and I am getting the same error, btw the other postman requests are working fine.

**Comment by subhi-huawei** [comment]
This is the related error:

![image](https://github.com/eclipse-edc/Samples/assets/167179433/cbae5534-080b-4fa8-8a01-e11efae8d701)

**Comment by ndr-brt** [comment]
please change the `odrl` context url to `http://www.w3.org/ns/odrl.jsonld`

**Comment by subhi-huawei** [comment]
Now it is working Thanks.
