### ISSUE TITLE
Make `transfer-05` runnable without the need for cloud accounts

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Samples#248]
# Feature Request

Currently to run the `transfer-05` samples there's the need for 2 cloud accounts: on Azure and Aws.
A good enhancement would be to introduce MinIO and Azurite to permit the transfer to run 100% locally.

This would permit the sample to be tested in an automated way like the other transfer samples.

## Which Areas Would Be Affected?

_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?

_Are there any requirements?_

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by ndr-brt** [comment]
> @ndr-brt I have exactly the same case where I have to use MinIO (so far I have everything running in Docker), but I did not find any useful information how to do it. Can you please help more regarding this topic?
> 
> What I tried: [eclipse-edc/Connector#3801](https://github.com/eclipse-edc/Connector/discussions/3801) [eclipse-edc/Technology-Aws#224](https://github.com/eclipse-edc/Technology-Aws/issues/224) #218
> 
> System env variables such as: EDC_AWS_ENDPOINT_OVERRIDE AWS_ENDPOINT_URL AWS_ENDPOINT_URL_S3 Also did not help...they seem not to work at all... As well as defining "endpointOverride" property in both the "dataAddress": {} and the "dataDestination": {}, my connector seems to ignore this property (I'm using edc 0.6.0)
> 
> My connector still throws this error:
> 
> software.amazon.awssdk.services.s3.model.NoSuchBucketException: The specified bucket does not exist (Service: S3, Status Code: 404, Request ID: 17DAFA308D9BBF2C, Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8)
> 
> I guess it tries to access the real AWS instance, not my local MinIO...The bucket is created and can be used from my other Python-based microservices, I also have some files inside the bucket, so I am totally sure that the bucket exists... 😅

I'd suggest to take a look at the automated tests in the `Technology-Aws` repository.
This one in particular runs with MinIO: https://github.com/eclipse-edc/Technology-Aws/blob/484fb469f21285e50b9474f74ffc3cd66cd5f0b6/extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java

**Comment by bpetrovbg** [comment]
@ndr-brt I am back again 😄, I confirm that the stuff from the [S3DataPlaneIntegrationTest.java](https://github.com/eclipse-edc/Technology-Aws/blob/484fb469f21285e50b9474f74ffc3cd66cd5f0b6/extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java) really works. Thanks a lot! If I have some time, I will contribute to the issue, or ask someone from my colleagues to do it, we know the right way... 😎
