### ISSUE TITLE
transfer/transfer-01-negotiation/Create a Policy on the provider error

### ISSUE THREAD

**Issue by NIdhogg-bug** [eclipse-edc/Samples#265]
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Bad Request</title>
</head>
<body><h2>HTTP ERROR 400 Bad Request</h2>
<table>
<tr><th>URI:</th><td>/management/v2/policydefinitions</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Bad Request</td></tr>
<tr><th>SERVLET:</th><td>EDC-management</td></tr>
</table>

</body>
</html>

**Comment by ndr-brt** [comment]
please add some details

**Comment by NIdhogg-bug** [comment]
> please add some details

![屏幕截图 2024-05-28 210148](https://github.com/eclipse-edc/Samples/assets/72740101/d6fa7713-9d00-41be-84d6-679f068295e1)
![Uploading 屏幕截图 2024-05-28 210256.png…]()
