### ISSUE TITLE
Incorrect description for sample 06

### ISSUE THREAD

**Issue by reisman234** [eclipse-edc/Samples#27]
# Bug Report

There are some small mistakes in the [transfer-06-consumer-pull-http sample](https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-06-consumer-pull-http), which leads to errors, while just following the readme file. 

- ports and URL Path don't match the configuration
- wrong build configuration for the backend-service
- (maybe) the wrong connector was addressed for the request to [check the transfer state](https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-06-consumer-pull-http#10-check-the-transfer-status). The current addressed returns just `ObjectNotFound`

I have created a git patch file which covers all the changes.
[transfer-06-sample.PATCH.txt](https://github.com/eclipse-edc/Samples/files/10792281/transfer-06-sample.PATCH.txt)

**Comment by Alexwilfriedo** [comment]
Hello @reisman234 ,
Thank you for bringing this up.
I'll do what I can to fix it and let you know

**Comment by Alexwilfriedo** [comment]
A new PR has been created related to this and correct the bug.
@reisman234 i'll keep you posted as soon as you can retest.
Thank you again for your contribution.
