### ISSUE TITLE
Add Tutorials about Creating Policies with Permissions

### ISSUE THREAD

**Issue by harnvo** [eclipse-edc/Samples#280]
# Feature Request

There seems to be no tutorial about how to negotiate a contract when we have policies with `permission`, `prohibition` or `obligation`. 

Including these values are very common for real-world scenerios, and it is very natural for beginners to try setting these values. However, simply following the tutorial without these values would not work (See [this issue](https://github.com/eclipse-edc/Samples/issues/279)).

I suggest adding a tutorial for this so that beginners would not need to check the connector source code to know what went wrong.

## Why Is the Feature Desired?

Laking this tutorial confuses beginners who wants to learn how to customize their policies.

## Solution Proposal

There are two solutions:

1. Provide another tutorial inside `transfer` folder
2. Change the `negotiate contract` in the `transfer-01-negotiation` tutorial, tell ppl we should copy and paste `permission`, `prohibition` and `obligation` inside `create-policy.json` into `policy` in `negotiate-contract.json`.

**Comment by ndr-brt** [comment]
samples about policy enforcement can be found in the `policy` folder, currently there's one pretty explanatory:
https://github.com/eclipse-edc/Samples/tree/main/policy/policy-01-policy-enforcement

**Comment by FantZero** [comment]
> samples about policy enforcement can be found in the `policy` folder, currently there's one pretty explanatory: https://github.com/eclipse-edc/Samples/tree/main/policy/policy-01-policy-enforcement

This location-limiting policy in [policy-01-policy-enforcement] is a good example, but i want to try more complex policies such as location-limiting, useTime-limiting, and useDuration-limiting at the same time
