### ISSUE TITLE
Missing transferType in sample transfer/streaming/streaming-01-http-to-http

### ISSUE THREAD

**Issue by klumbe** [eclipse-edc/Samples#334]
# Bug Report

## Describe the Bug

Sample: 
- transfer/streaming/streaming-01-http-to-http

Action:
- Starting the transfer process, using [transfer.json](https://github.com/eclipse-edc/Samples/blob/main/transfer/streaming/streaming-01-http-to-http/transfer.json):
```shell
curl -H 'Content-Type: application/json' -d @transfer/streaming/streaming-01-http-to-http/transfer.json -X POST "http://localhost:28181/management/v3/transferprocesses" -s | jq
```
Explanation:
When trying to start the transfer, the returned JSON states that the `transferType` is missing or blank.
No transfer process is started.

Error:
- 
### Expected Behavior

The transfer-process is started on both the consumer and provider end and an id for the transfer is returned:
```json
{
  "@type": "IdResponse",
  "@id": "<uuid>",
  "createdAt": 1730894147658,
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    "edc": "https://w3id.org/edc/v0.0.1/ns/",
    "odrl": "http://www.w3.org/ns/odrl/2/"
  }
}
```

### Observed Behavior
Error:
```json
[
  {
    "message": "mandatory value 'https://w3id.org/edc/v0.0.1/ns/transferType' is missing or it is blank",
    "type": "ValidationFailure",
    "path": "https://w3id.org/edc/v0.0.1/ns/transferType",
    "invalidValue": null
  }
]
```

## Steps to Reproduce

- Follow [Streaming-Sample-01]{https://github.com/eclipse-edc/Samples/blob/main/transfer/streaming/streaming-01-http-to-http/README.md} until starting the transfer process (see action above).

## Context Information
- Used commit: da78c98
- OS: Ubuntu 24.04

## Detailed Description

Things I tried to solve it:
- Adding a `transferType`of various kinds:
  - `HttpData-Push`
  - `HttpStreaming`
  - `Http Streaming`
  i.e.:
  ```json
  {
    "@context": {
      "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
    },
    "@type": "TransferRequest",
    "dataDestination": {
      "type": "HttpData",
      "baseUrl": "http://localhost:4000"
    },
    "protocol": "dataspace-protocol-http",
    "assetId": "stream-asset",
    "contractId": "{{contract-agreement-id}}",
    "connectorId": "provider",
    "counterPartyAddress": "http://localhost:18182/protocol",
    "transferType": "HttpData-PUSH"
  }
  ```
-> For `HttpData-PUSH` returns a proper ID, but on the provider, the following error is shown:
```shell
SEVERE 2024-11-06T12:55:48.969041699 TransferProcess: ID <uid>. Fatal error while Initiate data flow. Error details: DataPlane not found
WARNING 2024-11-06T12:55:48.969065369 DataPlane not found
```
The transfer-process is terminated shortly after.
-> The others claim an invalid `transferType` (expected):
```shell
[
  {
    "message": "Property transferType not valid: Failed to extract flow type from transferType HttpStreaming",
    "type": "InvalidRequest",
    "path": null,
    "invalidValue": null
  }
]
```
- Tried changing the `dataDestination/type`to `HttpStreaming` having the same issues

## Possible Implementation
-

**Comment by wolf4ood** [comment]
Hi @klumbe 

thanks for raising this, indeed the `transferType` is now required. 

I tried with `"transferType": "HttpData-PUSH"` in transfer.json and it worked

**Comment by ndr-brt** [comment]
Interesting that tests are still passing.
@klumbe would you like to provide a PR to fix this?

**Comment by ndr-brt** [comment]
> Yeah they pass but we build the request manually in code
> 
> https://github.com/eclipse-edc/Samples/blob/main/system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming01httpToHttpTest.java#L106
> 
> We probably just have to update the `transfer.json` file

definitely my fault :smiling_face_with_tear: test should use the `transfer.json` file as well

**Comment by klumbe** [comment]
> Hi @klumbe
> 
> thanks for raising this, indeed the `transferType` is now required.
> 
> I tried with `"transferType": "HttpData-PUSH"` in `transfer.json` and it worked
Hi @wolf4ood,
indeed, had a typo (case) in the ServiceExtension declaration, which caused the successive issues.



> Interesting that tests are still passing. @klumbe would you like to provide a PR to fix this?
Hi @ndr-brt,
I did. Is my first one, so let me know if there are issues with it.
Also provided a fix for the other open issue in the same rush.
