### ISSUE TITLE
Gradle is trying to download the wrong runtime-metamodel since milestone-9 release

### ISSUE THREAD

**Issue by JulianLegler** [eclipse-edc/Samples#56]
# Bug Report

## Describe the Bug
When trying to build the project, the building process will fail with 121 errors all stating:
```Could not resolve org.eclipse.edc:runtime-metamodel:0.0.1-SNAPSHOT``` 

### Expected Behavior
Downloading the correct runtime-metamodel and building successfully. 

### Observed Behavior
Failure of build process with message:

`Could not resolve org.eclipse.edc:runtime-metamodel:0.0.1-SNAPSHOT`

## Steps to Reproduce
1. clone repository
2. open in IDE (IntelliJ)
3. build Gradle

## Context Information
The new milestone-9 came just out. 

- Used version: milestone 8
- OS: Debian 11

## Detailed Description
The current gradle.properties:
```
groupId=org.eclipse.edc
edcVersion=0.0.1-milestone-8
defaultVersion=0.0.1-SNAPSHOT
javaVersion=11

# configure the build:
annotationProcessorVersion=0.0.1-SNAPSHOT
edcGradlePluginsVersion=0.0.1-SNAPSHOT
metaModelVersion=0.0.1-SNAPSHOT
```

## Possible Implementation
Something seems to broke since the release of milestone-9. A look in the gradle.properties seems to indicate, that the previous way of addressing the metaModelVersion is no longer working and breaks the current building process.

**Comment by ndr-brt** [comment]
This should have been solved by https://github.com/eclipse-edc/Samples/pull/60 and could be closed, please try it out
