### ISSUE TITLE
Getting a Problem with the curl command.

### ISSUE THREAD

**Issue by vpvikasp** [eclipse-edc/Samples#64]
# Bug Report 

## Describe the Bug
_A clear and concise description of the bug._ 
After building the connector step by step whenever i am running the first curl command i am not receiving any contract Id instead an error message is popping [{"message":"There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].","type":"InvalidRequest","path":null,"invalidValue":null}]

### Expected Behavior
_A clear and concise description of what you expected to happen._
Should Receive an UUID

### Observed Behavior
_A clear and concise description of what happened instead._
error- [{"message":"There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].","type":"InvalidRequest","path":null,"invalidValue":null}]

## Context Information
_Add any other context about the problem here._

- Used version [e.g. EDC v1.0.0]
- OS: [e.g. iOS, Windows]
- ...

## Detailed Description
_If applicable, add screenshots and logs to help explain your problem._
![WhatsApp Image 2023-06-05 at 10 13 39](https://github.com/eclipse-edc/Samples/assets/130986937/aa4202cd-e52a-486f-8640-059c4ece6b21)

## Possible Implementation
_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by ndr-brt** [comment]
What sample are you referring to?

**Comment by vpvikasp** [comment]
i am referring to building the Samples step by step.

**Comment by vpvikasp** [comment]
And after building the connector from EDC Samples and when i run the curl command i do not receive any UUID instead i get this always WARNING 2023-06-08T16:36:42.1070213 Error expanding JSON-LD structure
JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].] Kindly help me to solve this. @ndr-brt

**Comment by Julian-Marco** [comment]
I had the same problem but the answer in the other (duplicate) issue solved it for me: https://github.com/eclipse-edc/Samples/issues/63#issuecomment-1578287336

**Comment by vpvikasp** [comment]
@Julian-Marco i tried it and it still not working. Giving the same output. You can mail me here vpvikasp@gmail.com and then if you like you can guide me how u approached the issue. 
Thank you

**Comment by vpvikasp** [comment]
@Julian-Marco luckily it worked for me also. Now i would like to tell that if anyone is getting the same issue as i got then they just need to paste this edc.jsonld.http.enabled=true
edc.jsonld.https.enabled=true in the config.properties of consumer and provider and then again run the consumer and provider codes it will work. Also one more thing i found is the UUID command ( curl -X GET -H 'X-Api-Key: password' "http://localhost:9192/management/v2/contractnegotiations/{UUID}") in this command the X-Api-Key is in single inverted commas, change it to double it will not show error. Thanks for the help people.
