### ISSUE TITLE
loaders for http and https that the jsonld implementation uses for loading the context are not enabled by default.

### ISSUE THREAD

**Issue by rizwanmehmood94** [eclipse-edc/Samples#67]
Debugged into it a bit, the loaders for http and https that the jsonld implementation uses for loading the context are not enabled by default.

config.properties:
```properties
edc.jsonld.http.enabled=true
edc.jsonld.https.enabled=true
```

Cannot say if there are more problems,

_Originally posted by @FlorianWege-IESE in https://github.com/eclipse-edc/Samples/issues/63#issuecomment-1578287336_
  
Now this policy creating the issue after fixing the provided answer. 
![image](https://user-images.githubusercontent.com/51752121/245422193-b3e4c11a-6ba3-4385-8bfb-eac2fd821f86.png)

**Comment by FlorianWege-IESE** [comment]
Works for me (same json and endpoint) after adding the
```properties
edc.jsonld.http.enabled=true
edc.jsonld.https.enabled=true
```
lines to the config.properties file of the component (in my case https://github.com/eclipse-edc/Samples/blob/main/transfer/transfer-01-file-transfer/file-transfer-provider/config.properties).

**Comment by ndr-brt** [comment]
should be related to: https://github.com/eclipse-edc/Connector/issues/2952
