### ISSUE TITLE
Issue while running the Transfer sample 04: Open Telemetry.

### ISSUE THREAD

**Issue by junaidtk** [eclipse-edc/Samples#69]
I am trying to run the [Transfer sample 04](https://github.com/eclipse-edc/Samples/blob/main/transfer/transfer-04-open-telemetry/README.md): Open Telemetry. But after running the docker command it failed to start the `transfer-04-open-telemetry_consumer_1'. 

## Describe the Bug
Fails to run the Transfer sample 04: Open Telemetry.

### Expected Behavior
Expecting all the containers to start while running the docker up comand.

### Observed Behavior
`transfer-04-open-telemetry_consumer_1 exited with code 255
Aborting on container exit...
Stopping transfer-04-open-telemetry_provider_1 ... done
Stopping prometheus                            ... done
Stopping transfer-04-open-telemetry_jaeger_1   ... done
ERROR: 255`

I am also attaching the screenshot of the docker log from the docker. 
Docker error log for the consumer_1
<img width="1253" alt="Screenshot 2023-06-15 at 10 48 45 AM" src="https://github.com/eclipse-edc/Samples/assets/34098088/2da2fbf3-4ff2-4f56-b63e-627f8d8410de">

## Steps to Reproduce
1. Go to [Transfer sample 04](https://github.com/eclipse-edc/Samples/blob/main/transfer/transfer-04-open-telemetry/README.md): Open Telemetry
2. run 
`./gradlew transfer:transfer-04-open-telemetry:open-telemetry-consumer:build transfer:transfer-04-open-telemetry:open-telemetry-provider:build
docker-compose -f transfer/transfer-04-open-telemetry/docker-compose.yaml up --abort-on-container-exit`

**Comment by junaidtk** [comment]
This issue not resolved till now, but the ticket is closed. 

I am getting the same error as explained above, The below is the final result after running docker command.
`transfer-04-open-telemetry-consumer-1 exited with code 255
Aborting on container exit...
[+] Stopping 4/4
 ✔ Container transfer-04-open-telemetry-jaeger-1    Stopped                                                                                                                                            0.2s 
 ✔ Container prometheus                             Stopped                                                                                                                                            0.3s 
 ✔ Container transfer-04-open-telemetry-consumer-1  Stopped                                                                                                                                            0.0s 
 ✔ Container transfer-04-open-telemetry-provider-1  Stopped     `
 
 The docker error log is give below.
<img width="1253" alt="Screenshot 2023-06-19 at 10 22 18 AM" src="https://github.com/eclipse-edc/Samples/assets/34098088/ddf61e4b-e48a-4893-b283-f0c8e0fce1bd">

**Comment by juliapampus** [comment]
@majadlymhmd has discovered the error, WiP

**Comment by ndr-brt** [comment]
should have been fixed by #128 and #132
