### ISSUE TITLE
Port number of the consumer/provider in ReadMe.md is not consistent with the configulation.properies

### ISSUE THREAD

**Issue by miwamasa** [eclipse-edc/Samples#74]
# Bug Report

## Describe the Bug
Readme.md , the port number of provider and consumer may not accurate

### Expected Behavior

`consumer will listen on the ports 29191, 29193 (management API) , 29192 (IDS API)
 and 29194 (Data space protocol) `

`provider will listen on the ports 19191, 19193 (management API), 19192 (IDS API).
 and 19194 (Data space protocol)`

### Observed Behavior
at  "2. Run a consumer"

`Assuming you didn't change the ports in config files, the consumer will listen on the ports 29191, 29192 (management API) and 29292 (IDS API) and the provider will listen on the ports 12181, 19182 (management API) and 19282 (IDS API).`

## Steps to Reproduce
Just see the Readme.md

## Detailed Description
should be consistent with 

- consumer-configuration.properties 
- provider-configuration.properties

## Possible Implementation
_just fix

**Comment by ndr-brt** [comment]
hello, thanks for the issue, could you provide a PR to fix this?

**Comment by ndr-brt** [comment]
Likely this issue is outdated as samples changed a lot, please re-open if the issue persist
