### ISSUE TITLE
Is it possible to send customized body and auth headers on the proxy on transfer-06-consumer-pull-http sample?

### ISSUE THREAD

**Issue by skarampatakis** [eclipse-edc/Samples#98]
Hi, I have a question in regards of the transfer-06-consumer-pull-http sample. After the recent update I see that you can specify on the HttpAddress object the proxyBody, proxyQuery etc elements which will further customize the query send to the original data provider. On the end of the README you note that it is possible to add a proxyPath without being specified on the HttpAddress, so it is customizable when the request is done. Is it possbile to do the same with the proxyBody, proxyMethod and proxyQuery? 

Additionally, in the case the basuUrl is protected by Basic Auth, is it possible to specify the Auth header that will be passed on the original server? There is already the Authorization header, but if I get it correctly, this is used by EDC internally and never passed to the remote data server. 

Thank you very much in advance.

**Comment by xdxxxdx** [comment]
Same question here.
